[calculate]
port = "1234"
topic = "calculate"

[notifier]
file = "notifier.json"
token = "o.qnFIJyjSjpkBnDq24i8H3rdXVgH7TRz5"

[report]
port = "1235"

[store]
topic = "calculate"
group = "calculate-group"

[broker]
hosts = ["localhost:9092"]

[database]
host = "localhost"
port = "5432"
user = "root"
password = "root"
database = "report_db"