[package]
name = "notifier"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true }
libs = { workspace = true }
serde_json = { workspace = true }
clokwerk = "0.4.0"
chrono = "0.4.38"